# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0002_auto_20190223_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Popularity'),
        ),
    ]
